skinparam nodesep 50
skinparam ranksep 20
skinparam rectangle {
    fontcolor grey
    borderColor grey
    shadowing false
}
'skinparam linetype ortho

rectangle "NTOS\n" as NTOS {
    component winfsp
    interface "FSP_FSCTL\nTRANSACT" as FSP_FSCTL_TRANSACT
    winfsp -right- FSP_FSCTL_TRANSACT

    component winfuse #Salmon
    interface "FUSE_FSCTL\nTRANSACT" as FUSE_FSCTL_TRANSACT #Salmon
    winfuse -right- FUSE_FSCTL_TRANSACT

    winfsp .down.> winfuse: loads
    winfuse -up--( FSP_FSCTL_TRANSACT

    rectangle "LXCORE\n" as LXCORE {
        component wslfuse #Salmon
        interface "/dev/fuse" as devfuse #Salmon
        wslfuse -right- devfuse

        component lxldr

        lxldr .up.> wslfuse: loads
    }

    winfuse -[hidden]- wslfuse
    wslfuse -up--( FUSE_FSCTL_TRANSACT
}

component "Windows FS" as winfs
winfs -left-( FUSE_FSCTL_TRANSACT

component "Linux FS" as wslfs
wslfs -left-( devfuse

/'
skinparam linetype ortho

node NTOS {
    component winfsp #Salmon
    interface "FSP_FSCTL\nTRANSACT" as FSP_FSCTL_TRANSACT #Salmon
    winfsp -right- FSP_FSCTL_TRANSACT

    component winfuse #Salmon
    interface "FUSE_FSCTL\nTRANSACT" as FUSE_FSCTL_TRANSACT #Salmon
    winfuse -right- FUSE_FSCTL_TRANSACT

    winfsp .down.> winfuse: loads
    'winfsp -[hidden]- winfuse
    winfuse -up--( FSP_FSCTL_TRANSACT

    node LXCORE {
        component wslfuse #Salmon
        interface "/dev/fuse" as devfuse #Salmon
        wslfuse -right- devfuse

        component lxldr #Salmon

        lxldr .up.> wslfuse: loads
    }

    winfuse -[hidden]- wslfuse
    FSP_FSCTL_TRANSACT -[hidden]- FUSE_FSCTL_TRANSACT
    FUSE_FSCTL_TRANSACT -[hidden]- devfuse
}


'/
