left to right direction
skinparam componentStyle uml2
skinparam nodesep 50
skinparam ranksep 30
skinparam shadowing false
skinparam rectangle {
    fontcolor grey
    borderColor grey
    shadowing false
}
skinparam linetype ortho

rectangle NTOS {
    together dummy {
        component winfuse #Salmon
        interface "FUSE_FSCTL\nTRANSACT" as FUSE_FSCTL_TRANSACT #Salmon
        winfuse -right- FUSE_FSCTL_TRANSACT

        component winfsp
        interface "FSP_FSCTL\nTRANSACT" as FSP_FSCTL_TRANSACT
        winfsp -right- FSP_FSCTL_TRANSACT

        winfsp .up.> winfuse: loads
        winfuse -down-( FSP_FSCTL_TRANSACT
    }

    rectangle LXCORE {
        component wslfuse #Salmon
        interface "/dev/fuse" as devfuse #Salmon
        wslfuse -right- devfuse

        component lxldr

        lxldr .up.> wslfuse: loads
    }

    winfsp -[hidden]- wslfuse
    wslfuse -up-( FSP_FSCTL_TRANSACT
}

component "Windows\nWinFsp FS" as fspfs
fspfs -left-( FSP_FSCTL_TRANSACT

component "Windows\nFUSE FS" as winfs
winfs -left-( FUSE_FSCTL_TRANSACT

component "Linux\nFUSE FS" as wslfs
wslfs -left-( devfuse
