skinparam componentStyle uml2

component winfsp
component winfuse
component lxldr
component wslfuse
component "Windows FS" as winfs
component "Linux FS" as wslfs

winfsp -down- winfuse: FSP_FSCTL_TRANSACT
winfs -right- winfuse: FUSE_FSCTL_TRANSACT

lxldr .down.> wslfuse: load
wslfuse -left- winfuse: FUSE_FSCTL_TRANSACT
wslfuse -right- wslfs: /dev/fuse
