skinparam shadowing false
hide footbox

box "Originating Process Context"
    participant "Originating\nProcess" as OP
    participant "winfsp" as winfspOP
end box
box "File System Process Context"
    participant "winfsp" as winfspFS
    participant winfuse #Salmon
    participant "Windows\nFUSE FS" as FS
end box

activate OP
OP->winfspOP: I/O
deactivate OP
activate winfspOP
winfspOP-->winfspFS: Context Switch
deactivate winfspOP
activate winfspFS
winfspFS->winfuse: FSP_FSCTL_TRANSACT Req
deactivate winfspFS
activate winfuse
winfuse->FS: FUSE_FSCTL_TRANSACT Req
deactivate winfuse
activate FS
FS->FS: Process
activate FS
deactivate FS
FS->winfuse: FUSE_FSCTL_TRANSACT Rsp
deactivate FS
activate winfuse
winfuse->winfspFS: FSP_FSCTL_TRANSACT Rsp
deactivate winfuse
activate winfspFS
winfspFS-->OP: Context Switch and Return
deactivate winfspFS
activate OP
