skinparam shadowing false
hide footbox

box "Originating Process Context"
    participant "Originating\nProcess" as OP
    participant "winfsp" as winfspOP
end box
box "File System Process Context"
    participant "winfsp" as winfspFS
    participant wslfuse #Salmon
    participant "Linux\nFUSE FS" as FS
end box

activate OP
OP->winfspOP: I/O
deactivate OP
activate winfspOP
winfspOP-->winfspFS: Context Switch
deactivate winfspOP
activate winfspFS
winfspFS->wslfuse: FSP_FSCTL_TRANSACT Req
deactivate winfspFS
activate wslfuse
wslfuse->FS: /dev/fuse read
deactivate wslfuse
activate FS
FS->FS: Process
activate FS
deactivate FS
FS->wslfuse: /dev/fuse write
deactivate FS
activate wslfuse
wslfuse->winfspFS: FSP_FSCTL_TRANSACT Rsp
deactivate wslfuse
activate winfspFS
winfspFS-->OP: Context Switch and Return
deactivate winfspFS
activate OP
